<a href="https://colab.research.google.com/github/Arjun-coder5/AI-ML-Roadmap/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Creating Numpy Arrays :***

In [ ]:
#np array :
import numpy as np
np.array([1,2,3])


array([1, 2, 3])

In [ ]:
# 2d  arrray :
b = np.array([[1,2,3],[2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [ ]:
#3d array :

c = np.array([[1,2,3],[2,3,4],[4,5,6]])
print(c)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [ ]:
# dtype
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [ ]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#with reshape :
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#np.ones and np.zeros :
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random :
np.random.random((3,4))

array([[0.13086021, 0.23201844, 0.85760067, 0.70664148],
       [0.01446568, 0.23811364, 0.57515339, 0.37166126],
       [0.62240522, 0.47931444, 0.41618626, 0.65437981]])

In [ ]:
#np.linspace :
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity :
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ***Numpy Attributes :***

In [ ]:
a1 = np.arange(5)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
# ndim :
a1.ndim

1

In [ ]:
# shape :
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
#itemsize :
a2.itemsize

8

In [ ]:
# dtype :
print(a1.dtype)
print(a2.dtype)

int64
int64


# ***Changing DataType :***

In [ ]:
#as type:
a2.astype(np.int32)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]], dtype=int32)

In [ ]:
import numpy as np
a1 = np.arange(5)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

#Changing Data Type :

In [ ]:
#as type:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# ***Array Operations***

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
#Scaler Operation :

#Arithmatic
a1**2


array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
#relational Operators :
a2 >5
a2==5

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#Vector operation:
#Arithmatic :
a1 + a2
a1 - a2
a1 * a2
a1 / a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [ ]:
# max/min/sum/prod:
# 0 -> colm and 1 -> row :
print(a2.max())
print(a2.min())
print(a2.sum())
print(a2.prod())

23
12
210
647647525324800


In [ ]:
# mean/median/mode:

print(np.mean(a2))
print(np.median(a2))
print(stats.mode(a2, axis=0))

17.5
17.5
ModeResult(mode=array([12, 13, 14, 15]), count=array([1, 1, 1, 1]))


In [ ]:
# trigonometric fxn :

print(np.sin(a2))
print(np.cos(a2))
print(np.tan(a2))


[[-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]
 [ 0.91294525  0.83665564 -0.00885131 -0.8462204 ]]
[[ 0.84385396  0.90744678  0.13673722 -0.75968791]
 [-0.95765948 -0.27516334  0.66031671  0.98870462]
 [ 0.40808206 -0.54772926 -0.99996083 -0.53283302]]
[[-0.63585993  0.46302113  7.24460662 -0.8559934 ]
 [ 0.30063224  3.49391565 -1.13731371  0.15158947]
 [ 2.23716094 -1.52749853  0.00885166  1.58815308]]


In [ ]:
# Dot product :
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#Log and exponent :
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
#Round/floor/cell:
np.ceil(np.random.random((2,3))*100)

array([[24., 39., 16.],
       [61., 49., 70.]])

# ***Indexing And Slicing :***

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 =  np.arange(8).reshape(2,2,2)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[-1]

np.int64(9)

In [ ]:
a1[0]

np.int64(0)

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,2]

np.int64(6)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

np.int64(5)

In [ ]:
a3[1,1,0]

np.int64(6)

In [ ]:
a1[2:5]

array([2, 3, 4])

In [ ]:
a2[:,2]

In [5]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [11]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [18]:
a2[1,::3]

array([4, 7])

In [24]:
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [26]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [28]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [32]:
a3[1,:,1]

array([10, 13, 16])

In [33]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [37]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# ***iterating***

In [41]:
import numpy as np
a1 = np.arange(10)
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3


In [45]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [48]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# ***Reshaping :***

In [50]:
#Transpose :
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [54]:
#ravel:
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# ***Stacking***

In [55]:
#horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [56]:
#Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# ***Splitting***

In [57]:
#Horizontal Splitting :
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [60]:
#Vertical Splitting :
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]