<a href="https://colab.research.google.com/github/Arjun-coder5/AI-ML-Roadmap/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Creating Numpy Arrays :***

In [20]:
#np array :
import numpy as np
np.array([1,2,3])


array([1, 2, 3])

In [5]:
# 2d  arrray :
b = np.array([[1,2,3],[2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [6]:
#3d array :

c = np.array([[1,2,3],[2,3,4],[4,5,6]])
print(c)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [13]:
# dtype
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [14]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [28]:
#with reshape :
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
#np.ones and np.zeros :
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
# np.random :
np.random.random((3,4))

array([[0.13086021, 0.23201844, 0.85760067, 0.70664148],
       [0.01446568, 0.23811364, 0.57515339, 0.37166126],
       [0.62240522, 0.47931444, 0.41618626, 0.65437981]])

In [22]:
#np.linspace :
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [23]:
#np.identity :
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ***Numpy Attributes :***

In [30]:
a1 = np.arange(5)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [31]:
# ndim :
a1.ndim

1

In [33]:
# shape :
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [34]:
#itemsize :
a2.itemsize

8

In [35]:
# dtype :
print(a1.dtype)
print(a2.dtype)

int64
int64


# ***Changing DataType :***