<a href="https://colab.research.google.com/github/Arjun-coder5/AI-ML-Roadmap/blob/main/Numpy_Advance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy array vs Python lists :***

In [ ]:
#speed test :
#Python list:
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c = []
import time
start = time.time()
for i in range(len(a)):
  c.append(a[i]+b[i])
print(time.time()-start)

1.6694862842559814


In [ ]:
#numpy :
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start = time.time()
c = a+b
print(time.time()-start)

0.03456759452819824


In [ ]:
#memory :
a = [i for i in range(10000000)]
import sys
sys.getsizeof(a)


# ***Advance Indexing :***

In [ ]:
#Normal Indexing and Slicing :
import numpy as np
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [ ]:
a[1,2]

np.int64(5)

In [ ]:
#Fancy Indexing :
a
a[[0,2,3,5]]
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [26]:
#Boolean Indexing :
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[70, 49, 90,  5],
       [88, 67, 50, 90],
       [66, 63, 39, 25],
       [22, 16, 35, 51],
       [74, 76, 95, 92],
       [16, 61, 34, 89]])

In [28]:
#Find all the no greater than 50 :
a[a>50]

array([70, 90, 88, 67, 90, 66, 63, 51, 74, 76, 95, 92, 61, 89])

In [32]:
#Find even Numbers :
a[a%2==0]

array([70, 90, 88, 50, 90, 66, 22, 16, 74, 76, 92, 16, 34])

In [30]:
#Find all the numbers that are greater than 50 and are even :
a[(a>50) & (a%2==0)]

array([70, 90, 88, 90, 66, 74, 76, 92])

In [34]:
#Find all no that are not divisible by 7:
a[~(a%7==0)]

array([90,  5, 88, 67, 50, 90, 66, 39, 25, 22, 16, 51, 74, 76, 95, 92, 16,
       61, 34, 89])

# Broadcasting

The term Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.

The smaller array is "broadcast" across the larger array so that they have compatible shapes

In [ ]:
#Same Shape :
